/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-13.098, 2.85, -7.965]} rotation={[-1.706, 0.174, -0.48]} scale={[0.452, 0.235, 0.282]}>
        <mesh geometry={nodes.bearing_back_left_1_0.geometry} material={materials.Bearing} position={[0.92, 2.325, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_left_2_0.geometry} material={materials.Bearing} position={[0.69, 2.325, -0.091]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_right_1_0.geometry} material={materials.Bearing} position={[-0.929, 2.326, -0.091]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_right_2_0.geometry} material={materials.Bearing} position={[-0.699, 2.326, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_left_1_0.geometry} material={materials.Bearing} position={[0.922, -2.433, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_left_2_0.geometry} material={materials.Bearing} position={[0.692, -2.433, -0.091]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_right_1_0.geometry} material={materials.Bearing} position={[-0.927, -2.432, -0.091]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_right_2_0.geometry} material={materials.Bearing} position={[-0.697, -2.432, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.Deck_0.geometry} material={materials.deck} position={[-0.022, 0.143, 0.621]} scale={[1.172, 1, 1]} />
        <mesh geometry={nodes.Truck_back_0.geometry} material={materials.truck} position={[0.002, 2.199, 0.317]} rotation={[-0.025, 0, 0]} scale={[1.09, 1, 1]} />
        <mesh geometry={nodes.Truck_front_0.geometry} material={materials.truck} position={[-0.01, -2.306, 0.317]} rotation={[0.025, 0, Math.PI]} scale={[1.09, 1, 1]} />
        <mesh geometry={nodes.wheel_back_left_0.geometry} material={materials.wheel} position={[0.809, 2.327, -0.091]} rotation={[0, 1.571, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_back_right_0.geometry} material={materials.wheel} position={[-0.819, 2.325, -0.091]} rotation={[-1.455, -Math.PI / 2, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_front_left_0.geometry} material={materials.wheel} position={[0.811, -2.432, -0.091]} rotation={[-1.48, 1.571, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_front_right_0.geometry} material={materials.wheel} position={[-0.817, -2.434, -0.091]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[1, 1, 1.091]} />
      </group>
      <group position={[2.571, 1.338, 37.621]} rotation={[-1.564, -0.012, 0.003]} scale={[29.476, 6.819, 6.706]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-11.2, 0, 0]}>
              <mesh geometry={nodes['Skate_ramp_Material_#45_0'].geometry} material={materials.Material_45} position={[15.37, 34.965, -19.89]} rotation={[0.013, 0.018, -0.012]} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-12.93, 4.997, -7.941]} rotation={[-1.495, 0.498, 0.434]} scale={[2.175, 1.575, 0.981]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Extract3_Extract3_0.geometry} material={materials.Extract3} />
          <mesh geometry={nodes.Extract7_Extract7_0.geometry} material={materials.Extract7} />
          <mesh geometry={nodes.Pm3d_cylinder3d1_1_Pm3d_cylinder3d1_1_0.geometry} material={materials.Pm3d_cylinder3d1_1} />
          <mesh geometry={nodes.Pm3d_cylinder3d1_3_Pm3d_cylinder3d1_3_0.geometry} material={materials.Pm3d_cylinder3d1_3} />
          <mesh geometry={nodes.Pm3d_cylinder3d1_4_Pm3d_cylinder3d1_4_0.geometry} material={materials.Pm3d_cylinder3d1_4} />
          <mesh geometry={nodes.Pm3d_cylinder3d1_7_Pm3d_cylinder3d1_7_0.geometry} material={materials.Pm3d_cylinder3d1_7} />
          <mesh geometry={nodes.Pm3d_cylinder3d1_8_Pm3d_cylinder3d1_8_0.geometry} material={materials.Pm3d_cylinder3d1_8} />
          <mesh geometry={nodes.Pm3d_cylinder3d1_9_Pm3d_cylinder3d1_9_0.geometry} material={materials.Pm3d_cylinder3d1_9} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_Pm3d_cylinder3d2_0.geometry} material={materials.Pm3d_cylinder3d2} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_10_Pm3d_cylinder3d2_10_0.geometry} material={materials.Pm3d_cylinder3d2_10} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_11_Pm3d_cylinder3d2_11_0.geometry} material={materials.Pm3d_cylinder3d2_11} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_3_Pm3d_cylinder3d2_3_0.geometry} material={materials.Pm3d_cylinder3d2_3} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_5_Pm3d_cylinder3d2_5_0.geometry} material={materials.Pm3d_cylinder3d2_5} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_6_Pm3d_cylinder3d2_6_0.geometry} material={materials.Pm3d_cylinder3d2_6} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_7_Pm3d_cylinder3d2_7_0.geometry} material={materials.Pm3d_cylinder3d2_7} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_8_Pm3d_cylinder3d2_8_0.geometry} material={materials.Pm3d_cylinder3d2_8} />
          <mesh geometry={nodes.Pm3d_cylinder3d2_9_Pm3d_cylinder3d2_9_0.geometry} material={materials.Pm3d_cylinder3d2_9} />
          <mesh geometry={nodes.Pm3d_cylinder3d3_Pm3d_cylinder3d3_0.geometry} material={materials.Pm3d_cylinder3d3} />
          <mesh geometry={nodes.Pm3d_cylinder3d3_1_Pm3d_cylinder3d3_1_0.geometry} material={materials.Pm3d_cylinder3d3_1} />
          <mesh geometry={nodes.sponge_v03_sponge_v03_0.geometry} material={materials.sponge_v03} />
          <mesh geometry={nodes.sponge_v07_sponge_v07_0.geometry} material={materials.sponge_v07} />
          <mesh geometry={nodes.sponge_v07_01_sponge_v07_01_0.geometry} material={materials.sponge_v07_01} />
          <mesh geometry={nodes.sponge_v08_01_sponge_v08_01_0.geometry} material={materials.sponge_v08_01} position={[0.04, 0.347, -0.29]} rotation={[0.342, 0.17, 0.192]} />
          <mesh geometry={nodes.sponge_v08_02_sponge_v08_02_0.geometry} material={materials.sponge_v08_02} position={[0.136, -0.149, -0.226]} rotation={[0.128, -0.194, 0.208]} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0001.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0002.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0003.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0004.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0005.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0006.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0007.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0008.geometry} material={materials.sponge_v22_01} />
          <mesh geometry={nodes.sponge_v25_sponge_v25_0.geometry} material={materials.sponge_v25} />
        </group>
      </group>
      <group position={[16.97, 2.783, -7.935]} rotation={[-1.575, 0.298, -1.596]} scale={[0.561, 0.464, 0.532]}>
        <mesh geometry={nodes.bearing_back_left_1_0001.geometry} material={materials['Bearing.001']} position={[0.92, 2.325, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_left_2_0001.geometry} material={materials['Bearing.001']} position={[0.69, 2.325, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_right_1_0001.geometry} material={materials['Bearing.001']} position={[-0.929, 2.326, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_right_2_0001.geometry} material={materials['Bearing.001']} position={[-0.699, 2.326, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_left_1_0001.geometry} material={materials['Bearing.001']} position={[0.922, -2.433, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_left_2_0001.geometry} material={materials['Bearing.001']} position={[0.692, -2.433, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_right_1_0001.geometry} material={materials['Bearing.001']} position={[-0.927, -2.432, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_right_2_0001.geometry} material={materials['Bearing.001']} position={[-0.697, -2.432, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.Deck_0001.geometry} material={materials['deck.001']} position={[0, -0.079, 0.623]} scale={[1.172, 1, 1]} />
        <mesh geometry={nodes.Truck_back_0001.geometry} material={materials['truck.001']} position={[0.002, 2.199, 0.317]} rotation={[-0.025, 0, 0]} scale={[1.09, 1, 1]} />
        <mesh geometry={nodes.Truck_front_0001.geometry} material={materials['truck.001']} position={[-0.01, -2.306, 0.317]} rotation={[0.025, 0, Math.PI]} scale={[1.09, 1, 1]} />
        <mesh geometry={nodes.wheel_back_left_0001.geometry} material={materials['wheel.001']} position={[0.809, 2.327, -0.091]} rotation={[0, 1.571, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_back_right_0001.geometry} material={materials['wheel.001']} position={[-0.819, 2.325, -0.091]} rotation={[-1.455, -1.571, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_front_left_0001.geometry} material={materials['wheel.001']} position={[0.811, -2.432, -0.091]} rotation={[-1.48, Math.PI / 2, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_front_right_0001.geometry} material={materials['wheel.001']} position={[-0.817, -2.434, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[1, 1, 1.091]} />
      </group>
      <group position={[18.624, 5.686, -7.643]} rotation={[-1.55, 0.221, 3.032]} scale={[2.707, 1.672, 2.14]}>
        <group rotation={[1.583, -0.017, -0.011]}>
          <group position={[0.113, -0.007, -0.034]} rotation={[-0.005, 0, -0.024]}>
            <mesh geometry={nodes.Extract3_Extract3_0001.geometry} material={materials['Extract3.001']} />
            <mesh geometry={nodes.Extract7_Extract7_0001.geometry} material={materials['Extract7.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d1_1_Pm3d_cylinder3d1_1_0001.geometry} material={materials['Pm3d_cylinder3d1_1.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d1_3_Pm3d_cylinder3d1_3_0001.geometry} material={materials['Pm3d_cylinder3d1_3.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d1_4_Pm3d_cylinder3d1_4_0001.geometry} material={materials['Pm3d_cylinder3d1_4.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d1_7_Pm3d_cylinder3d1_7_0001.geometry} material={materials['Pm3d_cylinder3d1_7.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d1_8_Pm3d_cylinder3d1_8_0001.geometry} material={materials['Pm3d_cylinder3d1_8.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d1_9_Pm3d_cylinder3d1_9_0001.geometry} material={materials['Pm3d_cylinder3d1_9.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_Pm3d_cylinder3d2_0001.geometry} material={materials['Pm3d_cylinder3d2.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_10_Pm3d_cylinder3d2_10_0001.geometry} material={materials['Pm3d_cylinder3d2_10.001']} position={[-0.123, -0.025, 0.003]} rotation={[0.058, 0.015, 0.157]} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_11_Pm3d_cylinder3d2_11_0001.geometry} material={materials['Pm3d_cylinder3d2_11.001']} position={[-0.123, -0.025, 0.003]} rotation={[-0.002, -0.039, 0.172]} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_3_Pm3d_cylinder3d2_3_0001.geometry} material={materials['Pm3d_cylinder3d2_3.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_5_Pm3d_cylinder3d2_5_0001.geometry} material={materials['Pm3d_cylinder3d2_5.001']} position={[-0.123, -0.025, 0.003]} rotation={[-0.002, -0.039, 0.172]} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_6_Pm3d_cylinder3d2_6_0001.geometry} material={materials['Pm3d_cylinder3d2_6.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_7_Pm3d_cylinder3d2_7_0001.geometry} material={materials['Pm3d_cylinder3d2_7.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_8_Pm3d_cylinder3d2_8_0001.geometry} material={materials['Pm3d_cylinder3d2_8.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d2_9_Pm3d_cylinder3d2_9_0001.geometry} material={materials['Pm3d_cylinder3d2_9.001']} position={[-0.123, -0.025, 0.003]} rotation={[0.058, 0.015, 0.157]} />
            <mesh geometry={nodes.Pm3d_cylinder3d3_Pm3d_cylinder3d3_0001.geometry} material={materials['Pm3d_cylinder3d3.001']} />
            <mesh geometry={nodes.Pm3d_cylinder3d3_1_Pm3d_cylinder3d3_1_0001.geometry} material={materials['Pm3d_cylinder3d3_1.001']} />
            <mesh geometry={nodes.sponge_v03_sponge_v03_0001.geometry} material={materials['sponge_v03.001']} />
            <mesh geometry={nodes.sponge_v07_sponge_v07_0001.geometry} material={materials['sponge_v07.001']} />
            <mesh geometry={nodes.sponge_v07_01_sponge_v07_01_0001.geometry} material={materials['sponge_v07_01.001']} />
            <mesh geometry={nodes.sponge_v08_01_sponge_v08_01_0001.geometry} material={materials['sponge_v08_01.001']} />
            <mesh geometry={nodes.sponge_v08_02_sponge_v08_02_0001.geometry} material={materials['sponge_v08_02.001']} position={[0.075, 0.091, -0.025]} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0009.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0010.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0011.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0012.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0013.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0014.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0015.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0016.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v22_01_sponge_v22_01_0017.geometry} material={materials['sponge_v22_01.001']} />
            <mesh geometry={nodes.sponge_v25_sponge_v25_0001.geometry} material={materials['sponge_v25.001']} />
          </group>
        </group>
      </group>
      <group position={[8.205, 11.377, -32.284]} rotation={[-Math.PI / 2, 0, 3.094]}>
        <group scale={0.534}>
          <mesh geometry={nodes.Cube_DefaultMaterial_0.geometry} material={materials.DefaultMaterial} position={[-20.019, -29.32, -21.436]} rotation={[0, 0, 0.04]} scale={[0.38, 0.058, 0.121]} />
        </group>
      </group>
      <group position={[-12.274, -0.914, 38.401]} rotation={[-Math.PI / 2, 0, 0]} scale={[15.781, 13.073, 19.545]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Skate_ramp_Material_#45_0001'].geometry} material={materials['Material_45.001']} position={[-11.2, 0, 0]} />
          </group>
        </group>
      </group>
      <group position={[5.216, -0.745, -16.329]} rotation={[-Math.PI / 2, 0, 0]} scale={[15.446, 8.575, 4.346]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[27.5, 54.109, 3.447]} rotation={[-Math.PI / 2, 0, 0]} scale={29.448}>
            <mesh geometry={nodes.Sidewalls_s__0.geometry} material={materials['Scene_-_Root']} position={[-0.003, 0, 0.176]} rotation={[0, 0, -0.116]} />
          </group>
          <group position={[27.5, 62.411, -0.241]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Steps__0.geometry} material={materials['Scene_-_Root']} position={[0.001, 0, 0.052]} rotation={[0, 0, -0.116]} />
          </group>
          <mesh geometry={nodes.Frame__0.geometry} material={materials['Scene_-_Root']} position={[27.5, 44.835, -17.966]} rotation={[-Math.PI / 4, 0, 0]} scale={29.537} />
          <mesh geometry={nodes.Sidewalls__0.geometry} material={materials['Scene_-_Root']} position={[27.5, 41.312, 18.037]} scale={100} />
        </group>
      </group>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-0.523, 0.018, -6.329]} rotation={[-Math.PI, 0, 0]} scale={[-22.426, -1.717, -53.641]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[19.127, 1.345, -1.501]} scale={[0.937, 1.274, 8.75]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-10.396, 1.292, -9.167]} scale={[6.637, 1.247, 6.717]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.003']} position={[10.257, 1.914, -25.566]} rotation={[0, 1.518, 0]} scale={[4.787, 1.899, 5.21]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-18.648, 0.278, 11.447]} scale={[0.305, 0.297, 8.686]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
